In [1]:
import numpy as np

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.random.rand()

0.45331940148986727

In [10]:
np.random.rand(4)

array([9.06918257e-01, 2.36450099e-01, 3.88224089e-05, 6.87970155e-01])

In [11]:
np.random.rand(4,4)

array([[0.86045881, 0.4320881 , 0.85746638, 0.3985672 ],
       [0.53971661, 0.08997173, 0.24942646, 0.99419436],
       [0.9493475 , 0.4912943 , 0.89930183, 0.44259056],
       [0.86838689, 0.17750725, 0.28365098, 0.66684804]])

In [12]:
np.random.randint(1,15)

9

In [13]:
np.random.randint(1,100,(10,10))

array([[ 5, 86, 70, 91, 99,  9, 79,  2, 80, 99],
       [21, 60,  2,  2, 13, 35, 96, 61, 52,  2],
       [36, 26, 13, 95, 80,  6, 64, 80, 79, 35],
       [96, 85, 65, 40, 81, 17, 16, 22,  2, 64],
       [14, 93, 65, 59, 29, 98, 18, 67, 77, 10],
       [49, 32, 41, 55, 69, 66, 92, 30, 46, 13],
       [82, 52, 22, 96, 55, 82, 78, 36, 18,  3],
       [44, 66, 89, 96, 18, 24, 66, 74, 45, 64],
       [81, 90, 12, 76, 98, 56, 29,  8, 46, 14],
       [75, 55, 78,  3, 44, 21, 49, 69, 55,  7]])