In [1]:
import numpy as np

In [12]:
arr=np.random.randint(1,20,10)

In [3]:
matriz = arr.reshape(2,5)
matriz

array([[ 1, 10,  6,  5,  3],
       [11, 19,  5,  3, 15]])

In [4]:
arr.max()

19

In [6]:
matriz.max(0)

array([11, 19,  6,  5, 15])

In [7]:
arr.argmax()

6

In [9]:
matriz.argmax(0)

array([1, 1, 0, 0, 1], dtype=int64)

In [10]:
arr.min()

1

In [13]:
arr.ptp()

14