In [1]:
import numpy as np

In [6]:
arr = np.random.randint(1,10,(3,2))
arr

array([[8, 6],
       [2, 5],
       [2, 3]])

In [3]:
arr.shape

(3, 2)

In [4]:
arr

array([[5, 7],
       [6, 3],
       [5, 6]])

In [5]:
arr.reshape(1,6)

array([[5, 7, 6, 3, 5, 6]])

In [7]:
arr.reshape(2,3)

array([[8, 6, 2],
       [5, 2, 3]])

In [8]:
np.reshape(arr,(1,6))

array([[8, 6, 2, 5, 2, 3]])

In [9]:
arr

array([[8, 6],
       [2, 5],
       [2, 3]])

In [10]:
np.reshape(arr,(2,3),'C')

array([[8, 6, 2],
       [5, 2, 3]])

In [11]:
np.reshape(arr,(2,3),'F')

array([[8, 2, 5],
       [2, 6, 3]])

In [12]:
np.reshape(arr,(2,3),'A')

array([[8, 6, 2],
       [5, 2, 3]])